permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: ['jekyll-paginate']

paginate: 5
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

name: Rafael Monteiro
title: Rafael Monteiro
description: "Tips and thoughts about development and Information Security"
keywords: "infosec, IT, development, blog, web"
url: http://rafaelmonteiro.github.io
baseurl: ""
domain_name: rafaelmonteiro.github.io
# google_analytics: 
repo: http://github.com/rafaelmonteiro/rafaelmonteiro.github.io
disqus_shortname: "rafaelmonteiro"

author:
  name      : Rafael Monteiro
  image     : /assets/images/author.jpg
  email     : rfmsts@gmail.com
  url       : http://rafaelmonteiro.github.io
  twitter   : http://twitter.com/rfmsts
  github    : http://github.com/rafaelmonteiro
  linkedin  : http://linkedin.com/in/rafael-feitosa-monteiro-25649022
  bio       : "Desenvolvedor web."

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
